S3_BUCKET = 'download.livereload.com'

desc "Publish the web site"
task :publish do
    sh 's3_website', 'push'
    # sh 's3cmd', '-r', '-P', '--dry-run', '--no-delete-removed', 'sync', '_site/', "s3://livereload.com/"
end

desc "Publish the update metadata"
task :upd do
    sh 's3cmd', '-r', '-P', '--no-delete-removed', 'sync', '_site/update-metadata/', "s3://#{S3_BUCKET}/"
end
